### ISSUE TITLE
Více informací o erroru

### ISSUE THREAD

**Issue by Tlapi** [tomaskavalek/gosms#1]
https://github.com/tomaskavalek/gosms/blob/76667675092ef7322a91e1e469ade3829afdcb11/src/GoSMS/GoSMS.php#L122

Zde by bylo vhodné přidat více informací o chybě, kterou API vrátí, takto nám API často vrací "Another error" bez toho aniž bychom věděli co se odehrává za chybu.

**Comment by tomaskavalek** [comment]
Díky, vyřešeno vaším [pull requestem](https://github.com/tomaskavalek/gosms/pull/2).
